const AKEY='blackGoldAdmin';
const DAYS=[['Dom',0],['Seg',1],['Ter',2],['Qua',3],['Qui',4],['Sex',5],['Sáb',6]];
function AgetBookings(){return getBookings()}
function AsetBookings(v){saveBookings(v)}
function today(){return new Date().toISOString().slice(0,10)}
function byDateTime(a,b){return (a.date+a.time).localeCompare(b.date+b.time)}
function professionalName(id){return professionals.find(p=>p.id===id)?.name||'Profissional'}
function serviceName(id){return getServiceById(id)?.name||'Serviço'}
function renderFilter(){const s=document.getElementById('filterProfessional');s.innerHTML='<option value="all">Todos os profissionais</option>'+professionals.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');const ms=document.getElementById('manualProfessional');ms.innerHTML=professionals.filter(p=>p.id!=='qualquer').map(p=>`<option value="${p.id}">${p.name}</option>`).join('');const sv=document.getElementById('manualService');sv.innerHTML=services.map(s=>`<option value="${s.id}">${s.name} — ${fmtMoney(s.price)}</option>`).join('')}
function renderStats(){const d=document.getElementById('filterDate').value;const b=AgetBookings();const day=b.filter(x=>x.date===d);document.getElementById('statsGrid').innerHTML=`<div class="stat"><span>Hoje</span><b>${day.length}</b><small>agendamentos</small></div><div class="stat"><span>Confirmados</span><b>${day.filter(x=>x.status==='Confirmado').length}</b><small>para atender</small></div><div class="stat"><span>Concluídos</span><b>${day.filter(x=>x.status==='Concluído').length}</b><small>finalizados</small></div><div class="stat"><span>Faturamento</span><b>${fmtMoney(day.filter(x=>x.status!=='Cancelado').reduce((t,x)=>t+(getServiceById(x.serviceId)?.price||0),0))}</b><small>estimado no dia</small></div>`}
function statusClass(s){return s.toLowerCase().replace('í','i')}
function renderList(){const date=document.getElementById('filterDate').value,prof=document.getElementById('filterProfessional').value,status=document.getElementById('filterStatus').value;let b=AgetBookings().filter(x=>x.date===date&&(prof==='all'||x.professionalId===prof)&&(status==='all'||x.status===status)).sort(byDateTime);const el=document.getElementById('bookingList');if(!b.length){el.innerHTML='<div class="empty-state">Nenhum agendamento encontrado para esta data.</div>';return}el.innerHTML=b.map(x=>`<div class="booking-row"><div class="booking-time"><b>${x.time}</b><small>${getServiceById(x.serviceId)?.duration||30} min</small></div><div class="booking-client"><strong>${escapeHtml(x.name)}</strong><span>${serviceName(x.serviceId)} • ${professionalName(x.professionalId)}</span></div><div class="booking-phone"><a href="https://wa.me/55${digits(x.phone)}" target="_blank">${escapeHtml(x.phone)}</a></div><div><select class="status-select ${statusClass(x.status)}" data-id="${x.id}"><option ${x.status==='Confirmado'?'selected':''}>Confirmado</option><option ${x.status==='Concluído'?'selected':''}>Concluído</option><option ${x.status==='Cancelado'?'selected':''}>Cancelado</option></select></div><button class="delete-btn" data-delete="${x.id}" title="Excluir">×</button></div>`).join('');el.querySelectorAll('.status-select').forEach(s=>s.addEventListener('change',()=>{const arr=AgetBookings();const item=arr.find(x=>x.id===s.dataset.id);if(item){item.status=s.value;AsetBookings(arr);renderAll()}}));el.querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',()=>{if(confirm('Excluir este agendamento?')){AsetBookings(AgetBookings().filter(x=>x.id!==btn.dataset.delete));renderAll()}}))}
function renderAll(){renderStats();renderList()}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function digits(s){return String(s).replace(/\D/g,'')}
function openModal(id){document.getElementById(id).classList.add('show')}
function closeModals(){document.querySelectorAll('.modal').forEach(m=>m.classList.remove('show'))}
function auth(){if(localStorage.getItem(AKEY)==='1'){showDash()}else{document.getElementById('loginView').style.display='grid';document.getElementById('dashboardView').style.display='none'}}
function showDash(){document.getElementById('loginView').style.display='none';document.getElementById('dashboardView').style.display='block';document.getElementById('filterDate').value=today();renderFilter();loadConfig();renderAll()}
function loadConfig(){const c=getConfig();document.getElementById('cfgOpen').value=c.open;document.getElementById('cfgClose').value=c.close;document.getElementById('cfgBreakStart').value=c.breakStart;document.getElementById('cfgBreakEnd').value=c.breakEnd;document.getElementById('daysCheck').innerHTML=DAYS.map(([n,v])=>`<label><input type="checkbox" value="${v}" ${c.days.includes(v)?'checked':''}><span>${n}</span></label>`).join('')}
function setupAdmin(){document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();const email=document.getElementById('loginEmail').value,pw=document.getElementById('loginPassword').value;if(email==='admin@barbearia.com'&&pw==='123456'){localStorage.setItem(AKEY,'1');showDash()}else alert('E-mail ou senha inválidos.')});document.getElementById('logout').addEventListener('click',()=>{localStorage.removeItem(AKEY);auth()});document.getElementById('filterDate').addEventListener('change',renderAll);document.getElementById('filterProfessional').addEventListener('change',renderList);document.getElementById('filterStatus').addEventListener('change',renderList);document.getElementById('prevDay').addEventListener('click',()=>moveDate(-1));document.getElementById('nextDay').addEventListener('click',()=>moveDate(1));document.getElementById('openManual').addEventListener('click',()=>{document.getElementById('manualDate').value=document.getElementById('filterDate').value;openModal('manualModal')});document.getElementById('openConfig').addEventListener('click',()=>openModal('configModal'));document.querySelectorAll('[data-admin-close]').forEach(b=>b.addEventListener('click',closeModals));document.getElementById('manualForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target),item={id:crypto.randomUUID?.()||String(Date.now()),createdAt:new Date().toISOString(),name:fd.get('name').trim(),phone:fd.get('phone').trim(),serviceId:fd.get('serviceId'),professionalId:fd.get('professionalId'),date:fd.get('date'),time:fd.get('time'),email:'',status:'Confirmado'};const existing=getAvailableTimes(item.date,item.professionalId,getServiceById(item.serviceId).duration);if(!existing.includes(item.time)){alert('Esse horário está ocupado ou fora do funcionamento.');return}const arr=AgetBookings();arr.push(item);AsetBookings(arr);closeModals();e.target.reset();renderAll()});document.getElementById('configForm').addEventListener('submit',e=>{e.preventDefault();const days=[...document.querySelectorAll('#daysCheck input:checked')].map(x=>Number(x.value));if(!days.length){alert('Selecione ao menos um dia.');return}localStorage.setItem(CONFIG_KEY,JSON.stringify({open:document.getElementById('cfgOpen').value,close:document.getElementById('cfgClose').value,breakStart:document.getElementById('cfgBreakStart').value,breakEnd:document.getElementById('cfgBreakEnd').value,days}));closeModals();alert('Configurações salvas.');renderAll()})}
function moveDate(n){const d=new Date(document.getElementById('filterDate').value+'T12:00:00');d.setDate(d.getDate()+n);document.getElementById('filterDate').value=d.toISOString().slice(0,10);renderAll()}
document.addEventListener('DOMContentLoaded',()=>{setupAdmin();auth()});
