const STORAGE_KEY='blackGoldBookings';
const CONFIG_KEY='blackGoldConfig';
const defaultConfig={open:'09:00',close:'20:00',breakStart:'12:00',breakEnd:'13:00',days:[1,2,3,4,5,6]};
const services=[
 {id:'corte',name:'Corte de cabelo',price:40,duration:30,icon:'✂',desc:'Corte clássico, moderno ou personalizado.'},
 {id:'barba',name:'Barba',price:30,duration:20,icon:'◒',desc:'Barba alinhada com acabamento preciso.'},
 {id:'combo',name:'Cabelo + Barba',price:60,duration:50,icon:'✦',desc:'O combo completo para sair impecável.'},
 {id:'acabamento',name:'Acabamento',price:20,duration:15,icon:'⌁',desc:'Pezinho, contorno e pequenos retoques.'}
];
const professionals=[{id:'lucas',name:'Lucas',role:'Barbeiro Master',initial:'L'},{id:'gabriel',name:'Gabriel',role:'Barbeiro',initial:'G'},{id:'matheus',name:'Matheus',role:'Especialista em barba',initial:'M'},{id:'qualquer',name:'Qualquer disponível',role:'Primeiro horário disponível',initial:'✓'}];
function getBookings(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}}
function saveBookings(v){localStorage.setItem(STORAGE_KEY,JSON.stringify(v))}
function getConfig(){try{return {...defaultConfig,...JSON.parse(localStorage.getItem(CONFIG_KEY)||'{}')}}catch{return defaultConfig}}
function fmtMoney(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v)}
function fmtDate(v){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'full'}).format(new Date(v+'T12:00:00'))}
function renderServices(){const el=document.getElementById('serviceGrid');if(!el)return;el.innerHTML=services.map(s=>`<article class="service-card"><div class="service-icon">${s.icon}</div><h3>${s.name}</h3><p>${s.desc}</p><div class="service-bottom"><span class="service-price">${fmtMoney(s.price)}</span><span class="service-duration">${s.duration} min</span></div></article>`).join('');const sel=document.getElementById('serviceSelect');sel.innerHTML='<option value="">Selecione um serviço</option>'+services.map(s=>`<option value="${s.id}">${s.name} — ${fmtMoney(s.price)} / ${s.duration} min</option>`).join('')}
function renderTeam(){const el=document.getElementById('teamGrid');if(!el)return;el.innerHTML=professionals.filter(p=>p.id!=='qualquer').map(p=>`<article class="team-card"><div class="team-photo">${p.initial}</div><div class="team-info"><h3>${p.name}</h3><p>${p.role}</p></div></article>`).join('');const sel=document.getElementById('professionalSelect');sel.innerHTML='<option value="">Selecione um profissional</option>'+professionals.map(p=>`<option value="${p.id}">${p.name} — ${p.role}</option>`).join('')}
function setupMenu(){document.getElementById('menuToggle')?.addEventListener('click',()=>document.getElementById('mainNav').classList.toggle('open'));document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})))}
function dateValue(d){return d.toISOString().slice(0,10)}
function initDate(){const input=document.getElementById('dateSelect');if(!input)return;const now=new Date();input.min=dateValue(now);let d=new Date();while(!getConfig().days.includes(d.getDay()))d.setDate(d.getDate()+1);input.value=dateValue(d);input.addEventListener('change',renderTimes);renderTimes()}
function parseMin(s){const [h,m]=s.split(':').map(Number);return h*60+m}
function timeString(min){return String(Math.floor(min/60)).padStart(2,'0')+':'+String(min%60).padStart(2,'0')}
function getAvailableTimes(date,profId,duration){const c=getConfig();const day=new Date(date+'T12:00:00').getDay();if(!c.days.includes(day))return[];const all=getBookings().filter(b=>b.date===date && b.status!=='Cancelado' && (profId==='qualquer'||b.professionalId===profId));const out=[];const start=parseMin(c.open), end=parseMin(c.close), bs=parseMin(c.breakStart), be=parseMin(c.breakEnd);for(let t=start;t+duration<=end;t+=15){if(t>=bs&&t<be)continue;const collision=all.some(b=>{const bt=parseMin(b.time),bd=getServiceById(b.serviceId)?.duration||30;return t < bt+bd && t+duration>bt});if(!collision)out.push(timeString(t))}return out}
function getServiceById(id){return services.find(s=>s.id===id)}
function selected(){const s=getServiceById(document.getElementById('serviceSelect')?.value);const p=professionals.find(x=>x.id===document.getElementById('professionalSelect')?.value);return {s,p}}
function updateMini(){const box=document.getElementById('bookingSummary');if(!box)return;const {s,p}=selected();box.innerHTML=s&&p?`<strong>${s.name}</strong><br>${fmtMoney(s.price)} • ${s.duration} min<br>Profissional: ${p.name}`:'Selecione o serviço e o profissional.';}
function renderTimes(){const grid=document.getElementById('timeGrid');if(!grid)return;const {s,p}=selected();const date=document.getElementById('dateSelect').value;if(!s||!p||!date){grid.innerHTML='<div style="grid-column:1/-1;color:#888;padding:12px 0">Preencha os dados anteriores para ver os horários.</div>';return}const times=getAvailableTimes(date,p.id,s.duration);document.getElementById('availabilityMessage').textContent=times.length?`${times.length} horários`: 'Sem horários';grid.innerHTML=times.length?times.map(t=>`<button type="button" class="time-btn" data-time="${t}">${t}</button>`).join(''):'<div style="grid-column:1/-1;color:#888;padding:12px 0">Nenhum horário livre. Escolha outra data.</div>';document.getElementById('selectedTime').value='';grid.querySelectorAll('[data-time]').forEach(btn=>btn.addEventListener('click',()=>{grid.querySelectorAll('.time-btn').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');document.getElementById('selectedTime').value=btn.dataset.time}))}
function setStep(n){document.querySelectorAll('.form-step').forEach(x=>x.classList.toggle('active',x.dataset.step===String(n)));document.querySelectorAll('.steps span').forEach((x,i)=>x.classList.toggle('active',i<n));if(n===3){const {s,p}=selected();document.getElementById('finalSummary').innerHTML=`<strong>${s.name}</strong> — ${fmtMoney(s.price)}<br>${p.name}<br>${fmtDate(document.getElementById('dateSelect').value)} às ${document.getElementById('selectedTime').value}`}}
function formSetup(){const s=document.getElementById('serviceSelect'),p=document.getElementById('professionalSelect');s?.addEventListener('change',()=>{updateMini();renderTimes()});p?.addEventListener('change',()=>{updateMini();renderTimes()});document.getElementById('nextStep1')?.addEventListener('click',()=>{if(!s.value||!p.value){alert('Selecione o serviço e o profissional.');return}setStep(2)});document.getElementById('nextStep2')?.addEventListener('click',()=>{if(!document.getElementById('selectedTime').value){alert('Selecione um horário.');return}setStep(3)});document.querySelectorAll('[data-prev]').forEach(b=>b.addEventListener('click',()=>{const active=document.querySelector('.form-step.active');setStep(Number(active.dataset.step)-1)}));document.getElementById('bookingForm')?.addEventListener('submit',e=>{e.preventDefault();const {s,p}=selected();const date=document.getElementById('dateSelect').value,time=document.getElementById('selectedTime').value,name=document.getElementById('clientName').value.trim(),phone=document.getElementById('clientPhone').value.trim(),email=document.getElementById('clientEmail').value.trim();if(!name||!phone||!date||!time)return;const booking={id:crypto.randomUUID?.()||String(Date.now()),createdAt:new Date().toISOString(),serviceId:s.id,professionalId:p.id,date,time,name,phone,email,status:'Confirmado'};const current=getBookings();if(!getAvailableTimes(date,p.id,s.duration).includes(time)){alert('Esse horário acabou de ser ocupado. Escolha outro.');setStep(2);renderTimes();return}current.push(booking);saveBookings(current);const person=p.name==='Qualquer disponível'?'profissional disponível':p.name;document.getElementById('successText').innerHTML=`${name}, seu agendamento foi marcado para <strong>${date.split('-').reverse().join('/')}</strong> às <strong>${time}</strong> com ${person}.`;const msg=encodeURIComponent(`Olá! Meu agendamento está confirmado na Black & Gold.\n\nCliente: ${name}\nServiço: ${s.name}\nData: ${date.split('-').reverse().join('/')} às ${time}\nProfissional: ${person}`);document.getElementById('successWhatsapp').href=`https://wa.me/?text=${msg}`;document.getElementById('successModal').classList.add('show');document.getElementById('successModal').setAttribute('aria-hidden','false');e.target.reset();setStep(1);initDate()});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{document.getElementById('successModal').classList.remove('show')}))}
function init(){renderServices();renderTeam();setupMenu();formSetup();initDate();const wa=document.getElementById('whatsappLink');if(wa)wa.href='https://wa.me/?text='+encodeURIComponent('Olá! Gostaria de agendar um horário na Black & Gold Barbers.');}
document.addEventListener('DOMContentLoaded',init);
